Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1536, in __call__
  File "Tkinter.pyc", line 587, in callit
  File "main.py", line 17, in load_wemo
NameError: global name 'ip' is not defined
